### ISSUE TITLE
I am interested in your code

### ISSUE THREAD

**Issue by vonyrhatoe** [RicardoPereiraIST/youtube-download#1]
please add the threading code to extract the url without downloading,
I want to try your code on my server, I only need the direct url to be included in html video playback

**Comment by RicardoPereiraIST** [comment]
This code is not very sustainable as is. It was made a while ago with only what I needed in mind (until they add their own threading system). Maybe I will consider doing it properly one day, but it is not in my plans so far. Nonetheless, there is probably someone already who did a proper threading wrapper which you might be able to use.

Regardless, how many urls are you trying to extract on your server at a time? I'm just asking because threading will only be helpfull if you are extracting multiple at the same time, which is usually not the case, and the bottleneck might not even be your cpu but the network.
